#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=0:05:00
#PBS -q batch
#PBS -N run
#PBS -j oe

#cat $PBS_NODEFILE
cd /home/koutrosj/project
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./a.out 100 2000

