#!/bin/bash
#PBS -l nodes=16:ppn=12
#PBS -l walltime=00:15:00
#PBS -q batch
#PBS -N run
#PBS -j oe

#cat $PBS_NODEFILE

export TAU_MAKEFILE=/opt/sw/tau/x86_64/lib/Makefile.tau-mpi-pdt

cd ~/project

for i in {2..16}
do

    mpiexec -np $i --map-by ppr:1:node --hostfile $PBS_NODEFILE ./hiv_bcast.cx 10 2000

    pprof > pprof_numrank_$i.txt

    rm profile.*

done

mv pprof_numrank_* pprof/
