#!/bin/bash
#PBS -l nodes=2:ppn=1
#PBS -l walltime=00:00:10
#PBS -q batch
#PBS -N run
#PBS -j oe

#cat $PBS_NODEFILE

cd ~/project/results
rm gen_*

cd ~/project
mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./a.out 1 50
