#!/bin/bash
#PBS -l nodes=16:ppn=12
#PBS -l walltime=00:15:00
#PBS -q batch
#PBS -N run
#PBS -j oe

#cat $PBS_NODEFILE

export TAU_MAKEFILE=/opt/sw/tau/x86_64/lib/Makefile.tau-mpi-pdt

cd ~/project

mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./hiv_halo.cx 100 2000

mpiexec -np 4 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./hiv_halo.cx 100 1000

mpiexec -np 16 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./hiv_halo.cx 100 500
