#!/bin/bash
#PBS -l nodes=8:ppn=12
#PBS -l walltime=00:10:00
#PBS -q batch
#PBS -N run
#PBS -j oe

#cat $PBS_NODEFILE

export TAU_MAKEFILE=/opt/sw/tau/x86_64/lib/Makefile.tau-mpi-pdt

cd ~/project/pprof

rm pprof_*
rm profile.*

cd ~/project

for i in {2..8}
do

    mpiexec -np $i --map-by ppr:1:node --hostfile $PBS_NODEFILE ./hiv.cx 10 2000

    pprof > pprof/pprof_numrank_$i.txt

done

rm profile.*
